version: '3.8'

services:

  rabbitmq:

    image: "rabbitmq:3.13-management"

    hostname: "rabbitmq"

    ports:

      - "5672:5672"

      - "15672:15672"
  
    healthcheck:
      test: ["CMD","rabbitmq-diagnostics","ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 

    volumes:
      - .:/app
    
    ports:
     - "8000:8000"

    depends_on:
      rabbitmq:
        condition: service_healthy
    
  worker:

    build: .

    command: celery -A app.core.celery_app.celery worker --loglevel=info

    volumes:
      - .:/app

    depends_on:
      rabbitmq:
        condition: service_healthy






